using Microsoft.EntityFrameworkCore;
using MiniHTC.Models;
namespace MiniHTC.Data;
public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();
        if (db.Database.IsNpgsql())   // bảng thêm sau — EnsureCreated không tạo trên Postgres đã tồn tại
            foreach (var sql in new[]{
                "CREATE TABLE IF NOT EXISTS public.\"Masters\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Category\" text NOT NULL DEFAULT '', \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Status\" text NOT NULL DEFAULT '1', \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
                "CREATE TABLE IF NOT EXISTS public.\"Dealers\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"DealerCode\" text NOT NULL DEFAULT '', \"DealerName\" text NOT NULL DEFAULT '', \"BUCode\" text NULL, \"ProvinceCode\" text NULL, \"Address\" text NULL, \"Phone\" text NULL, \"Fax\" text NULL, \"Email\" text NULL, \"TaxCode\" text NULL, \"Status\" text NOT NULL DEFAULT '1', \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
                "CREATE TABLE IF NOT EXISTS public.\"CarPrices\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"ModelCode\" text NOT NULL DEFAULT '', \"SpecCode\" text NULL, \"ColorCode\" text NULL, \"Price\" numeric NOT NULL DEFAULT 0, \"Vat\" numeric NOT NULL DEFAULT 10, \"Status\" text NOT NULL DEFAULT '1', \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
                "CREATE TABLE IF NOT EXISTS public.\"Customers\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"CustomerCode\" text NOT NULL DEFAULT '', \"CustomerName\" text NOT NULL DEFAULT '', \"Phone\" text NULL, \"IdCard\" text NULL, \"TaxCode\" text NULL, \"Address\" text NULL, \"Email\" text NULL, \"ProvinceCode\" text NULL, \"Status\" text NOT NULL DEFAULT '1', \"CreatedAt\" timestamp NOT NULL DEFAULT now())",
            }) try { await db.Database.ExecuteSqlRawAsync(sql); } catch { }
        if (!await db.Orgs.AnyAsync(o => o.Id == TenantContext.DefaultOrgId))
            db.Orgs.Add(new Org { Id = TenantContext.DefaultOrgId, Name = "HTC", ApiKey = "demo-htc" });
        if (!await db.Areas.AnyAsync())
            db.Areas.AddRange(
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MB", AreaName = "Miền Bắc", Status = "1" },
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MT", AreaName = "Miền Trung", Status = "1" },
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MN", AreaName = "Miền Nam", Status = "1" });
        await db.SaveChangesAsync();
    }
}
