using Microsoft.EntityFrameworkCore;
using MiniHTC.Models;
namespace MiniHTC.Data;
public static class Seeder
{
    public static async Task SeedAsync(AppDbContext db)
    {
        await db.Database.EnsureCreatedAsync();
        if (db.Database.IsNpgsql())   // bảng Masters thêm sau — EnsureCreated không tạo trên Postgres đã tồn tại
            try { await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS public.\"Masters\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"OrgId\" uuid NOT NULL, \"Category\" text NOT NULL DEFAULT '', \"Code\" text NOT NULL DEFAULT '', \"Name\" text NOT NULL DEFAULT '', \"Status\" text NOT NULL DEFAULT '1', \"CreatedAt\" timestamp NOT NULL DEFAULT now())"); } catch { }
        if (!await db.Orgs.AnyAsync(o => o.Id == TenantContext.DefaultOrgId))
            db.Orgs.Add(new Org { Id = TenantContext.DefaultOrgId, Name = "HTC", ApiKey = "demo-htc" });
        if (!await db.Areas.AnyAsync())
            db.Areas.AddRange(
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MB", AreaName = "Miền Bắc", Status = "1" },
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MT", AreaName = "Miền Trung", Status = "1" },
                new Area { OrgId = TenantContext.DefaultOrgId, AreaCode = "MN", AreaName = "Miền Nam", Status = "1" });
        await db.SaveChangesAsync();
    }
}
